### ISSUE TITLE
Dependencywheel not working properly

### ISSUE THREAD

**Issue by Enij** [czxa/sankeywheel#1]
![image](https://user-images.githubusercontent.com/17040379/71156322-77bbaf80-2248-11ea-8628-3970dc41774c.png)
For whatever reason just having Highcharter's renderHighchart and highchartOutput functions makes it so that Sankeywheel's type "dependencywheel" is not showing up. The exact situation works fine when the type is changed to "sankey." If I remove Highcharter's functions from the code, the type "dependencywheel" works fine and it looks great.
![image](https://user-images.githubusercontent.com/17040379/71156472-bea9a500-2248-11ea-9fdb-7e97e14f3107.png)
The next code picture shows the code to repeat how to achieve that situation (pretty much adding Highcharter's functions to working example that came with Sankeywheel).
![image](https://user-images.githubusercontent.com/17040379/71156516-d08b4800-2248-11ea-862d-40f80de65849.png)

**Comment by czxa** [comment]
I think that was because there are some conflicts between highcharter and sankeywheel. There is no solution yet. It is recommended not to use the two R packages at the same time, sorry for that.

**Comment by czxa** [comment]
你可以使用 highcharter 绘制桑基图和和弦图了！可以参考下面的代码：

桑基图：

```r
library(sankeywheel)
sankeydf -> df

library(highcharter)

# 桑基图
highchart() %>% 
  hc_chart(type = 'sankey') %>% 
  hc_add_series(keys = c('from', 'to', 'weight'),
                data = list_parse2(df),
                name = "Sankey demo series") %>% 
  hc_title(text = 'Highcharts 桑基图') %>% 
  hc_add_theme(hc_theme_sandsignika(
    chart = list(
      divBackgroundImage = NULL,
      style = list(background = "url(https://www.highcharts.com/samples/graphics/sand.png)", 
                   fontFamily = "Source Han Serif")
    )
  )) %>% 
  hc_exporting(enabled = T) %>% 
  hc_credits(enabled = T,
             text = "©RStata 绘制",
             href = "https://tidyfriday.cn")
```

![](https://mdniceczx.oss-cn-beijing.aliyuncs.com/image_20200829120646.png)

和弦图：

```r
highchart() %>% 
  hc_chart(type = 'dependencywheel') %>% 
  hc_add_series(keys = c('from', 'to', 'weight'),
                data = list_parse2(df),
                name = "Demo series",
                dataLabels = list(
                  color = '#333',
                  distance = 20
                ),
                size = '95%') %>% 
  hc_title(text = 'Highcharts 和弦图') %>% 
  hc_add_theme(hc_theme_sandsignika(
    chart = list(
      divBackgroundImage = NULL,
      style = list(background = "url(https://www.highcharts.com/samples/graphics/sand.png)", 
                   fontFamily = "Source Han Serif")
    )
  )) %>% 
  hc_exporting(enabled = T) %>% 
  hc_credits(enabled = T,
             text = "©RStata 绘制",
             href = "https://tidyfriday.cn")
```

![](https://mdniceczx.oss-cn-beijing.aliyuncs.com/image_20200829120727.png)
